
drop database IF EXISTS JQ;

create database IF NOT EXISTS JQ;

USE JQ;

CREATE TABLE Module
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	PARENTID INT(10) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	URL VARCHAR(255),
	VALID BOOLEAN NOT NULL,
	PRIMARY KEY(ID)

)AUTO_INCREMENT=1;


CREATE TABLE Property
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	TYPE INT(11) NOT NULL,
	VALID BOOLEAN NOT NULL,
	PRIMARY KEY(ID)
)AUTO_INCREMENT=1;

CREATE TABLE PropertyOption
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	PID INT(11) NOT NULL,
	VALUE VARCHAR(255) NOT NULL,
	VALID BOOLEAN NOT NULL,
	PRIMARY KEY(ID)
)AUTO_INCREMENT=1;

CREATE TABLE ModuleConfig
(

	ID INT(11) NOT NULL AUTO_INCREMENT,
	ModuleID INT(11) NOT NULL,
	PropertyID INT(11) NOT NULL,
	ConfigID INT(11) NOT NULL,
	VALID BOOLEAN NOT NULL,
	PRIMARY KEY(ID)

)AUTO_INCREMENT=1;


CREATE TABLE ModuleData
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	FieldID INT(11) NOT NULL,
	ParentID INT(11) NOT NULL,
	Data VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
	
)AUTO_INCREMENT=1;

CREATE TABLE Employee
(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	EMPID VARCHAR(255) NOT NULL,
	EMPNAME VARCHAR(255) NOT NULL,
	ENABLE BOOLEAN,
	VALID BOOLEAN,
	PRIMARY KEY(ID)

);

CREATE TABLE Role
(
	ID INT(10) NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	ROLES VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE Population
(
	ID INT(10) NOT NULL AUTO_INCREMENT,
	
	PID VARCHAR(255) NOT NULL,
	
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY(ID)



);


CREATE TABLE WhiteList
(
	ID INT(10) NOT NULL AUTO_INCREMENT,
	
	IP VARCHAR(255) NOT NULL,
	
	STATUS BOOLEAN,
	PRIMARY KEY(ID)

);

